#!/usr/bin/env python3
#
# Mock-stub unit test for navpose_set_fixed_config_script.py.
#
# WHY A MOCK-STUB TEST (not a real rospy/nepi_sdk import test):
# This machine has no built catkin workspace (no devel/setup.bash). rospy
# itself IS genuinely importable here (real /opt/ros/noetic install:
# python3 -c "import rospy" succeeds), but `nepi_sdk.nepi_ros` /
# `nepi_interfaces.msg` / `nepi_api.messages_if` are NOT importable --
# nepi_sdk/nepi_interfaces/nepi_api are custom NEPI packages that only
# exist inside the device's catkin workspace (nepi_interfaces.msg classes
# in particular are generated by catkin's message_generation at build
# time; nothing has been built here). Confirmed directly this session:
#   python3 -c "import nepi_sdk"        -> ModuleNotFoundError
#   python3 -c "import nepi_interfaces" -> ModuleNotFoundError
#   python3 -c "import nepi_api"        -> ModuleNotFoundError
# So, matching the sibling test files in this directory (e.g.
# test_navpose_config_script.py, test_led_auto_level_process_script.py),
# this test stubs rospy entirely (a real rospy.Publisher()/rospy.spin()
# would try to contact a ROS master), plus nepi_sdk.nepi_ros,
# nepi_api.messages_if.MsgIF, and nepi_interfaces.msg.{UpdateNavPose,
# UpdateString, NavPose}.
#
# The stub message classes use __slots__ populated from the field lists
# read directly out of the current .msg files this session
# (src/nepi_interfaces/msg/UpdateNavPose.msg, NavPose.msg,
# UpdateString.msg) -- not guessed -- so that if the script under test
# referenced a renamed/removed field (e.g. the old quaternion-based
# orientation fields, or an old RBX-style field name) it would raise an
# AttributeError here, exactly the class of bug this session was full of
# before the two reference scripts (drone_inspection_demo_mission_script.py
# / drone_follow_object_mission_script.py) were fixed.
#
# navpose_set_fixed_config_script.py's __init__ does ALL of its publishing
# work directly in __init__ (there is no separate timer/callback method to
# exercise) -- both publishers (`fixed_navpose_pub`, `comp_topic_pub`) are
# local variables, not stored on self. To still be able to assert on what
# was actually published, the fake rospy.Publisher stub records every
# instance it creates in a shared class-level registry keyed by resolved
# topic name, which the test inspects after construction.
#
# Run directly with:
#   python3 -m unittest tests.test_navpose_set_fixed_config_script -v
# (from the nepi_sample_auto_scripts/ directory)

import importlib.util
import os
import sys
import types
import unittest

SCRIPT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT_PATH = os.path.join(SCRIPT_DIR, "navpose_set_fixed_config_script.py")

BASE_NAMESPACE = "/nepi/device1/"


def _install_stub_modules():
    """Inject stub rospy / nepi_sdk.nepi_ros / nepi_api.messages_if /
    nepi_interfaces.msg modules into sys.modules and return the previous
    sys.modules entries (or None) so the caller can restore them
    afterward, plus handles to the fake Publisher registry and message
    classes so the test can inspect what was published.
    """

    # ---------------------------------------------------------------
    # rospy stub -- only the surface navpose_set_fixed_config_script.py
    # uses: Publisher, sleep, spin.
    # ---------------------------------------------------------------
    rospy_stub = types.ModuleType("rospy")

    publisher_registry = {}  # topic -> list of _FakePublisher instances
    publish_call_order = []  # topic names, in the order .publish() was called

    class _FakePublisher:
        def __init__(self, topic, msg_class, queue_size=1):
            self.topic = topic
            self.msg_class = msg_class
            self.queue_size = queue_size
            self.published = []
            publisher_registry.setdefault(topic, []).append(self)

        def publish(self, *args, **kwargs):
            if args:
                self.published.append(args[0])
            else:
                self.published.append(self.msg_class(**kwargs))
            publish_call_order.append(self.topic)

    rospy_stub.Publisher = _FakePublisher
    rospy_stub.sleep = lambda secs=0: None  # must NOT actually block the test
    rospy_stub.spin = lambda: None  # must NOT block the test
    rospy_stub.is_shutdown = lambda: False
    rospy_stub.signal_shutdown = lambda reason=None: None
    rospy_stub.init_node = lambda *a, **k: None
    rospy_stub.loginfo = lambda *a, **k: None
    rospy_stub.logwarn = lambda *a, **k: None
    rospy_stub.logerr = lambda *a, **k: None
    rospy_stub.logdebug = lambda *a, **k: None

    # ---------------------------------------------------------------
    # nepi_sdk / nepi_sdk.nepi_ros stub -- signatures match the current
    # nepi_ros.py: init_node(name), get_node_name(), get_base_namespace(),
    # wait_for_topic(topic_name, ...).
    # ---------------------------------------------------------------
    nepi_sdk_pkg = types.ModuleType("nepi_sdk")
    nepi_ros_stub = types.ModuleType("nepi_sdk.nepi_ros")

    nepi_ros_stub.init_node = lambda name, disable_signals=False: None
    nepi_ros_stub.get_node_name = lambda: "navpose_set_fixed_config"
    nepi_ros_stub.get_base_namespace = lambda: BASE_NAMESPACE
    nepi_ros_stub.is_shutdown = lambda: False

    def _wait_for_topic(topic_name, timeout=60, log_name_list=None,
                         topics_list=None, types_list=None):
        # Real nepi_ros.wait_for_topic() polls the live ROS graph for a
        # topic whose name *contains* topic_name and returns the fully
        # resolved topic string. Simulate that resolution deterministically.
        if topic_name.startswith("/"):
            return topic_name
        return BASE_NAMESPACE + topic_name.lstrip("/")

    nepi_ros_stub.wait_for_topic = _wait_for_topic
    nepi_sdk_pkg.nepi_ros = nepi_ros_stub

    # ---------------------------------------------------------------
    # nepi_api / nepi_api.messages_if.MsgIF stub -- records every
    # pub_info/pub_warn/pub_debug/pub_error call so the test can assert
    # the script uses ONLY this (current) logging convention and never
    # falls back to the removed nepi_msg.publishMsgInfo(self, msg) style.
    # ---------------------------------------------------------------
    nepi_api_pkg = types.ModuleType("nepi_api")
    messages_if_stub = types.ModuleType("nepi_api.messages_if")

    class _FakeMsgIF:
        def __init__(self, log_name=None):
            self.log_name = log_name
            self.calls = []

        def pub_info(self, msg, **kwargs):
            self.calls.append(("info", msg))

        def pub_warn(self, msg, **kwargs):
            self.calls.append(("warn", msg))

        def pub_debug(self, msg, **kwargs):
            self.calls.append(("debug", msg))

        def pub_error(self, msg, **kwargs):
            self.calls.append(("error", msg))

    messages_if_stub.MsgIF = _FakeMsgIF
    nepi_api_pkg.messages_if = messages_if_stub

    # ---------------------------------------------------------------
    # nepi_interfaces.msg stub -- field lists read directly out of the
    # current .msg files this session:
    #   UpdateNavPose.msg: name, name2, name3, navpose (NavPose)
    #   UpdateString.msg:  name, name2, name3, value
    #   NavPose.msg: header, navpose_frame, navpose_description,
    #     frame_nav, frame_altitude, frame_depth,
    #     has_location, time_location, latitude, longitude, location_m_per_sec,
    #     has_heading, time_heading, heading_deg, heading_m_per_sec,
    #     has_orientation, time_orientation, roll_deg, pitch_deg, yaw_deg,
    #     roll_deg_per_sec, pitch_deg_per_sec, yaw_deg_per_sec,
    #     has_position, time_position, x_m, y_m, z_m,
    #     x_m_per_sec, y_m_per_sec, z_m_per_sec,
    #     has_altitude, time_altitude, altitude_m, geoid_height_meters,
    #     altitude_m_per_sec,
    #     has_depth, time_depth, depth_m, depth_m_per_sec,
    #     has_pan_tilt, time_pan_tilt, pan_deg, tilt_deg,
    #     pan_tilt_heading_deg, pan_tilt_x_m, pan_tilt_y_m, pan_tilt_z_m,
    #     pan_tilt_roll_deg, pan_tilt_pitch_deg, pan_tilt_yaw_deg
    # Using __slots__ so that any reference to a field NOT in this list
    # (e.g. a stale quaternion-based orientation field from the old API)
    # raises an AttributeError here instead of silently succeeding.
    # ---------------------------------------------------------------
    nepi_interfaces_pkg = types.ModuleType("nepi_interfaces")
    nepi_interfaces_msg_stub = types.ModuleType("nepi_interfaces.msg")

    _NAVPOSE_FIELDS = (
        "header", "navpose_frame", "navpose_description",
        "frame_nav", "frame_altitude", "frame_depth",
        "has_location", "time_location", "latitude", "longitude", "location_m_per_sec",
        "has_heading", "time_heading", "heading_deg", "heading_m_per_sec",
        "has_orientation", "time_orientation", "roll_deg", "pitch_deg", "yaw_deg",
        "roll_deg_per_sec", "pitch_deg_per_sec", "yaw_deg_per_sec",
        "has_position", "time_position", "x_m", "y_m", "z_m",
        "x_m_per_sec", "y_m_per_sec", "z_m_per_sec",
        "has_altitude", "time_altitude", "altitude_m", "geoid_height_meters",
        "altitude_m_per_sec",
        "has_depth", "time_depth", "depth_m", "depth_m_per_sec",
        "has_pan_tilt", "time_pan_tilt", "pan_deg", "tilt_deg",
        "pan_tilt_heading_deg", "pan_tilt_x_m", "pan_tilt_y_m", "pan_tilt_z_m",
        "pan_tilt_roll_deg", "pan_tilt_pitch_deg", "pan_tilt_yaw_deg",
    )

    class _FakeNavPose:
        __slots__ = _NAVPOSE_FIELDS

        def __init__(self, **kwargs):
            for field in _NAVPOSE_FIELDS:
                default = False if field.startswith("has_") else (
                    "" if field in ("navpose_frame", "navpose_description",
                                     "frame_nav", "frame_altitude", "frame_depth")
                    else (None if field == "header" else 0.0)
                )
                setattr(self, field, default)
            for key, value in kwargs.items():
                setattr(self, key, value)

    class _FakeUpdateNavPose:
        __slots__ = ("name", "name2", "name3", "navpose")

        def __init__(self, name="", name2="", name3="", navpose=None):
            self.name = name
            self.name2 = name2
            self.name3 = name3
            self.navpose = navpose

    class _FakeUpdateString:
        __slots__ = ("name", "name2", "name3", "value")

        def __init__(self, name="", name2="", name3="", value=""):
            self.name = name
            self.name2 = name2
            self.name3 = name3
            self.value = value

        def __repr__(self):
            return ("UpdateString(name=%r, name2=%r, name3=%r, value=%r)"
                     % (self.name, self.name2, self.name3, self.value))

    nepi_interfaces_msg_stub.NavPose = _FakeNavPose
    nepi_interfaces_msg_stub.UpdateNavPose = _FakeUpdateNavPose
    nepi_interfaces_msg_stub.UpdateString = _FakeUpdateString
    nepi_interfaces_pkg.msg = nepi_interfaces_msg_stub

    stub_modules = {
        "rospy": rospy_stub,
        "nepi_sdk": nepi_sdk_pkg,
        "nepi_sdk.nepi_ros": nepi_ros_stub,
        "nepi_api": nepi_api_pkg,
        "nepi_api.messages_if": messages_if_stub,
        "nepi_interfaces": nepi_interfaces_pkg,
        "nepi_interfaces.msg": nepi_interfaces_msg_stub,
    }

    previous = {}
    for name, mod in stub_modules.items():
        previous[name] = sys.modules.get(name)
        sys.modules[name] = mod

    handles = {
        "publisher_registry": publisher_registry,
        "publish_call_order": publish_call_order,
        "NavPose": _FakeNavPose,
        "UpdateNavPose": _FakeUpdateNavPose,
        "UpdateString": _FakeUpdateString,
    }
    return previous, handles


def _restore_modules(previous):
    for name, mod in previous.items():
        if mod is None:
            sys.modules.pop(name, None)
        else:
            sys.modules[name] = mod


class TestNavposeSetFixedConfigScript(unittest.TestCase):
    """Imports navpose_set_fixed_config_script.py against stub modules for
    the modules unavailable/broken in this environment (nepi_sdk.nepi_ros,
    nepi_interfaces.msg, nepi_api.messages_if) plus a fully-stubbed rospy
    (to avoid contacting a ROS master and to avoid the real rospy.spin()
    blocking forever), drives the real __init__ path end-to-end (this
    script does all its work in __init__, there is no separate
    timer/callback), and confirms no broken attribute/field references
    remain post-API-drift-fix.
    """

    @classmethod
    def setUpClass(cls):
        previous, handles = _install_stub_modules()
        try:
            spec = importlib.util.spec_from_file_location(
                "navpose_set_fixed_config_script_under_test", SCRIPT_PATH
            )
            cls.module = importlib.util.module_from_spec(spec)
            sys.modules[spec.name] = cls.module
            spec.loader.exec_module(cls.module)
        finally:
            _restore_modules(previous)
        cls.UpdateNavPose = handles["UpdateNavPose"]
        cls.UpdateString = handles["UpdateString"]
        cls.NavPose = handles["NavPose"]
        # IMPORTANT: the script does `import rospy` (and `from nepi_sdk import
        # nepi_ros`, `from nepi_api.messages_if import MsgIF`, `from
        # nepi_interfaces.msg import ...`) at MODULE level, so those names are
        # bound ONCE, here, at exec_module time -- to the stub objects/classes
        # created by *this* _install_stub_modules() call. Re-installing fresh
        # stub modules on every subsequent test (as a naive per-test
        # `_install_stub_modules()` call would do) would create a new
        # publisher_registry that the already-imported script module never
        # sees, since its `rospy` name still points at the original stub
        # module object. So the single registry captured here is reused
        # (and cleared) across every test instead.
        cls.publisher_registry = handles["publisher_registry"]
        cls.publish_call_order = handles["publish_call_order"]

    def _build_instance(self):
        self.publisher_registry.clear()
        self.publish_call_order.clear()
        instance = self.module.navpose_set_fixed_config()
        return instance, self.publisher_registry

    # ------------------------------------------------------------
    # 1) Clean import + expected module-level constants present.
    # ------------------------------------------------------------
    def test_module_imports_cleanly(self):
        self.assertTrue(hasattr(self.module, "navpose_set_fixed_config"))
        self.assertEqual(self.module.NAVPOSE_TARGET_FRAME, "base_frame")
        self.assertEqual(len(self.module.START_GEOPOINT), 3)
        self.assertEqual(len(self.module.START_ORIENTATION_DEGS), 3)

    # ------------------------------------------------------------
    # 2) Source no longer references the removed nepi_msg module or the
    #    old flat nav_pose_mgr / quaternion-conversion API.
    # ------------------------------------------------------------
    def test_source_has_no_removed_nepi_msg_api(self):
        with open(SCRIPT_PATH) as f:
            src = f.read()
        self.assertNotIn("import nepi_msg", src)
        self.assertNotIn("nepi_msg.", src)
        self.assertNotIn("publishMsgInfo(", src)
        self.assertNotIn("createMsgPublishers(", src)
        self.assertIn("MsgIF", src)

    def test_source_has_no_removed_navpose_mgr_or_quaternion_api(self):
        # The module docstring intentionally documents the OLD nav_pose_mgr
        # API names AND the old nepi_nav.convert_rpy2quat()/QuaternionStamped
        # quaternion path in prose (matching the drone_* reference scripts'
        # documentation style, explaining *why* they're no longer needed) --
        # what must actually be absent is any *executable usage*: an import
        # line for the modules that would be needed to call them, or a
        # call/topic-name form with a trailing "(" the way live (non-comment)
        # code would reference them.
        lines = []
        with open(SCRIPT_PATH) as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith("#"):
                    continue  # skip docstring/comment-only lines
                lines.append(line)
        code_only_src = "".join(lines)

        for removed in (
            "set_init_gps_fix(", "set_init_heading(", "set_init_orientation(",
            "reinit_solution(", "enable_gps_clock_sync(",
            "import nepi_ros_interfaces", "from nepi_ros_interfaces",
            "nepi_nav.convert_rpy2quat(", "QuaternionStamped(",
        ):
            self.assertNotIn(removed, code_only_src)
        # These modules are only ever mentioned in prose (to explain why
        # they're no longer needed) -- confirm there is no real import
        # statement for either, anywhere in the file (not just in code
        # lines), since an "import tf" or "import nepi_nav" line itself
        # never starts with "#".
        with open(SCRIPT_PATH) as f:
            full_src = f.read()
        self.assertNotIn("\nimport tf\n", full_src)
        self.assertNotIn("import nepi_nav", full_src)
        self.assertNotIn("from nepi_sdk import nepi_nav", full_src)

        self.assertIn("set_frame_fixed_navpose", full_src)
        self.assertIn("set_frame_comp_topic", full_src)

    # ------------------------------------------------------------
    # 3) Full __init__ path runs against the stubbed current API with no
    #    AttributeError/TypeError, and the fixed-navpose publish carries
    #    the correct target frame + NavPose field values.
    # ------------------------------------------------------------
    def test_init_publishes_fixed_navpose_with_expected_fields(self):
        instance, registry = self._build_instance()

        # msg_if was constructed via the current MsgIF(log_name=...) API
        # and used for logging (not the removed nepi_msg module).
        self.assertEqual(instance.msg_if.log_name, "navpose_set_fixed_config")
        self.assertTrue(any(level == "info" for level, _ in instance.msg_if.calls))

        fixed_topic = BASE_NAMESPACE + "navpose_mgr/set_frame_fixed_navpose"
        self.assertIn(fixed_topic, registry)
        fixed_pubs = registry[fixed_topic]
        self.assertEqual(len(fixed_pubs), 1)
        fixed_pub = fixed_pubs[0]
        self.assertIs(fixed_pub.msg_class, self.UpdateNavPose)
        self.assertEqual(len(fixed_pub.published), 1)

        published = fixed_pub.published[0]
        self.assertIsInstance(published, self.UpdateNavPose)
        self.assertEqual(published.name, "base_frame")
        navpose = published.navpose
        self.assertIsInstance(navpose, self.NavPose)
        self.assertTrue(navpose.has_location)
        self.assertEqual(navpose.latitude, 47.6540828)
        self.assertEqual(navpose.longitude, -122.3187578)
        self.assertTrue(navpose.has_altitude)
        self.assertEqual(navpose.altitude_m, 0.0)
        self.assertTrue(navpose.has_heading)
        self.assertEqual(navpose.heading_deg, 88.0)
        self.assertTrue(navpose.has_orientation)
        self.assertEqual(navpose.roll_deg, 10.0)
        self.assertEqual(navpose.pitch_deg, 20.0)
        self.assertEqual(navpose.yaw_deg, 30.0)

    # ------------------------------------------------------------
    # 4) The comp-topic publisher points each of the four expected
    #    components at 'Fixed' for the target frame's init stage, using
    #    the current UpdateString field layout (not a removed RBX-style
    #    or nav_pose_mgr-style message).
    # ------------------------------------------------------------
    def test_init_sets_comp_topics_to_fixed(self):
        instance, registry = self._build_instance()

        comp_topic = BASE_NAMESPACE + "navpose_mgr/set_frame_comp_topic"
        self.assertIn(comp_topic, registry)
        comp_pubs = registry[comp_topic]
        self.assertEqual(len(comp_pubs), 1)
        comp_pub = comp_pubs[0]
        self.assertIs(comp_pub.msg_class, self.UpdateString)

        self.assertEqual(len(comp_pub.published), 4)
        by_comp = {msg.name2: msg for msg in comp_pub.published}
        self.assertEqual(
            set(by_comp.keys()), {"location", "altitude", "heading", "orientation"}
        )
        for comp_name, msg in by_comp.items():
            self.assertIsInstance(msg, self.UpdateString)
            self.assertEqual(msg.name, "base_frame")
            self.assertEqual(msg.name3, "init")
            self.assertEqual(msg.value, "Fixed")

    # ------------------------------------------------------------
    # 5) Publish ordering: the fixed navpose values are stored BEFORE the
    #    comp-topic components are switched to 'Fixed' (matches the
    #    documented navpose_mgr semantics -- 'Fixed' needs stored fixed
    #    values to be meaningful).
    # ------------------------------------------------------------
    def test_fixed_navpose_published_before_comp_topics(self):
        instance, _registry = self._build_instance()
        fixed_topic = BASE_NAMESPACE + "navpose_mgr/set_frame_fixed_navpose"
        comp_topic = BASE_NAMESPACE + "navpose_mgr/set_frame_comp_topic"

        first_fixed_idx = self.publish_call_order.index(fixed_topic)
        first_comp_idx = self.publish_call_order.index(comp_topic)
        self.assertLess(
            first_fixed_idx, first_comp_idx,
            "fixed navpose values must be published before the comp-topic "
            "components are switched to 'Fixed', since 'Fixed' only has "
            "meaning once fixed values are stored for the frame",
        )

    # ------------------------------------------------------------
    # 6) cleanup_actions doesn't raise and still uses msg_if.pub_info
    #    (not a removed nepi_msg call).
    # ------------------------------------------------------------
    def test_cleanup_actions_does_not_raise(self):
        instance, _ = self._build_instance()
        instance.cleanup_actions()
        self.assertTrue(any(level == "info" for level, _ in instance.msg_if.calls))


if __name__ == "__main__":
    unittest.main(verbosity=2)
